query FindProductionQuery ($sort: String, $limit: Int, $start: Int, $where: JSON ) {
  productions(sort: $sort, limit: $limit, start: $start, where: $where) {
    _id
    title
    description
    picto
    color
    images {
      url              
    }
  }
}